# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Diff-Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diff-Practice
	pod 'DifferenceKit'
	pod 'Differ'
	pod 'IGListKit', '~> 4.0.0'

end
